### ISSUE TITLE
Send Cypress dashboard run url to slack?

### ISSUE THREAD

**Issue by josephcc** [bdimitrovski/cypress-healthcheck#1]
Thanks for this repo! It helped me out a lot setting up cypress-slack integration. 

Sorry if this is completely out of scope of this project, but I was wondering if there's a way to include the run URL to the Cypress dashboard. I'm not sure if this would be done through `mocha-spec-json-output-reporter` or directly from Cypress?

**Comment by josephcc** [comment]
Found a solution here
https://docs.cypress.io/guides/guides/module-api.html#cypress-run

**Comment by bdimitrovski** [comment]
Hey @josephcc! I'm glad you like this project and that you found it useful :) Also, great to hear that you were able to solve the issue with including the run URL to the Cypress dashboard. The Cypress module API is really powerful in that sense, so you can customize it to your needs.
