### ISSUE TITLE
Fails to report Failed Tests

### ISSUE THREAD

**Issue by mhornbacher** [bdimitrovski/cypress-healthcheck#3]
If the tests fail cypress returns with a non-0 error code causing the script to fail before the `reportToSlack.js` file is run

Perhaps this is a limitation of cypress?

**Comment by bdimitrovski** [comment]
This should not be the case though, as the npm script has the ; between connected commands, which basically means, perform the 2nd npm command no matter the result of the first. Can you please share a bit more context on this one so I can help you better? A screenshot, video, reproducible example etc would be helpful.

**Comment by NguyenDa18** [comment]
It worked for me out of the box, just needed to specify the Slack webhook in a new .env file. Perhaps that is the cause of the error?

**Comment by mhornbacher** [comment]
I am running it on windows and it seems that the `;` is being added to the cypress command 😨!!

I'll try to isolate everything and make a minimum viable reproduction of the bug on sunday... for now I wrote my own implementation to bypass this for production 🤷‍♂

**Comment by bdimitrovski** [comment]
> I am running it on windows and it seems that the `;` is being added to the cypress command 😨!!
> 
> I'll try to isolate everything and make a minimum viable reproduction of the bug on sunday... for now I wrote my own implementation to bypass this for production 🤷‍♂

@mhornbacher That's weird, I wouldn't know how it works on windows machines, since I've only been running this on Mac and Linux machines and servers. If you could make a minimum viable reproduction that would be great, otherwise, you could also share your own implementation to see how the issue can be fixed for all systems.

**Comment by bdimitrovski** [comment]
@NguyenDa18 Yes, you need to specify your own .env file which will be used for the Slack webhook key.

**Comment by NguyenDa18** [comment]
@bdimitrovski Do you think this issue can be closed? Adding the environment variable should fix the issue.

**Comment by bdimitrovski** [comment]
@NguyenDa18 Apologies for the very belated response, I have only noticed this just now. Yes, I think it can be closed, as adding an environment variable should fix the issue.
