### ISSUE TITLE
changing webhook to another product

### ISSUE THREAD

**Issue by helenou** [bdimitrovski/cypress-healthcheck#8]
Hello @bdimitrovski ,

I'm not a slack user but could use the webhook solution to send out on error alerts to our chat.
There is webhook available too, only I'm not sure how and when health-check.json is generated, it's called in utils/reportToSlack.js

looking forward to hearing from you

**Comment by bdtobii** [comment]
Hi @helenou, which chat application do you use/want to use instead of Slack? `health-check.json` is generated at the end of a test run, and then is being parsed, then finally sent to Slack if there are test failures.

**Comment by helenou** [comment]
> Hi @helenou, which chat application do you use/want to use instead of Slack? `health-check.json` is generated at the end of a test run, and then is being parsed, then finally sent to Slack if there are test failures.

Hi @bdtobii i want to use Rocket.chat as a chat application with cypress alerts. 
Thanks for your reply

**Comment by bdtobii** [comment]
@helenou You could probably use something like https://docs.rocket.chat/guides/administration/administration/integrations#incoming-webhook-script to send messages to a Rocket Chat.

I can't tell you more about the specific details of the integration, but their documentation seems quite extensive, so you should be able to work things out from there. 

Additionally, you could also leverage the Rocket Chat's Node API: https://github.com/qeesung/rocketchat-node and use it to send messages if certain conditions (e.g. failed tests) are fulfilled.

**Comment by bdtobii** [comment]
Hi @helenou, have you been able to use the script with Rocket chat? If yes, I'd like to close this issue.
